### ISSUE TITLE
Error with nested collections

### ISSUE THREAD

**Issue by mleez** [UniversalViewer/universalviewer#447] opened 2017-04-11 21:24 UTC
The UV is loading fine when I have a collection that contains a collection that contains a manifest (collection depth of two). For collections with a depth of three and beyond however, I am getting an undefined property error in bundle.js.

Here is a successful example (collection depth of two):
* https://collections.ushmm.org/uvtest/hierarchy-test-success/
  * https://collections.ushmm.org/uvtest/hierarchy-test-success/collection-top.json
  * https://collections.ushmm.org/uvtest/hierarchy-test-success/collection-1.json
  * https://collections.ushmm.org/uvtest/hierarchy-test-success/manifest-1.json

Here is an example where the error occurs (collection depth of three):
* https://collections.ushmm.org/uvtest/hierarchy-test-error/
  * https://collections.ushmm.org/uvtest/hierarchy-test-error/collection-top.json
  * https://collections.ushmm.org/uvtest/hierarchy-test-error/collection-1.json
  * https://collections.ushmm.org/uvtest/hierarchy-test-error/collection-2.json
  * https://collections.ushmm.org/uvtest/hierarchy-test-error/manifest-1.json

The only difference between these two examples is the existence of collection-2.json in the second one.

@edsilv believes the issue is stemming from this section of the Manifold library and asked me to link to it here: https://github.com/viewdir/manifold/blob/master/src/Bootstrapper.ts#L82

**Comment by demiankatz** [comment] 2017-04-18 12:56
When I try to reproduce @mleez's error in Firefox, I get this slightly more specific error message:

<pre>
TypeError: manifest is undefined
http://universalviewer.io/vendor/uv/lib/bundle.min.js
Line 4
</pre>

@edsilv, does that help narrow down the cause?

It does seem possible that this is related to the highlighted code in Manifold; maybe that needs to be some kind of loop rather than an if statement. I don't think I've looked at that logic since it was factored out of the UV itself, so I'll need to refamiliarize myself when I have a bit more time to spare. I'm not sure what the test suite in Manifold looks like (assuming there is one at all), but this seems like the sort of thing that would make a good smoke test.

Also, for what it's worth, Villanova's digital library has an arbitrary nesting of collections -- you can see our top level at https://digital.library.villanova.edu/Collection/vudl:3/IIIF. However, the first collection inside the top-level collection does contain manifests, so if the issue is indeed related to multiple nested collection-only manifests, it makes sense that our collection is not triggering the problem.

**Comment by edsilv** [comment] 2017-04-20 10:43
@demiankatz Currently we don't have a test suite for Manifold. I think @sdellis has been experimenting with jsdom (https://www.npmjs.com/package/jsdom) for testing ViewDir components, which seems like a good option. Creating a test for this should be the first priority.

**Comment by sdellis** [comment] 2017-04-20 13:44
[Here is an example](https://github.com/viewdir/component-boilerplate-redux/blob/master/tests/browser.js) of the jsdom integration/feature tests for a boilerplate component. This only tests what happens in the browser, but it's fast and can be run with `gulp test`. We discussed unit testing as well, but there wasn't a clear cut solution for that given the stack, and it seemed like the feature tests might be enough at the time. I think adding feature tests like this would only be able to tell you that this scenario breaks the UV, not the source of the problem. Good to have, but may not help with debugging.

Finally, @edsilv I wonder if generating sourcemaps from gulp/browserify would help debug this?

**Comment by edsilv** [comment] 2017-04-21 10:20
@sdellis I haven't got as far as adding sourcemaps to https://github.com/viewdir/gulp-tasks/ yet... Would definitely be nice to be able to run the vscode debugger on manifold in the same way you can with manifesto, but being able to hit breakpoints in the TS files.

**Comment by tomcrane** [comment] 2017-07-20 15:33
Another example (collections of collections)

http://universalviewer.io/uv.html?manifest=http://wellcomelibrary.org/service/collections/

**Comment by edsilv** [comment] 2017-11-27 13:57
closing as fixed by https://github.com/UniversalViewer/universalviewer/commit/ec4ad8c5744abede2fb5016a7ab14e62973a3105

**Closed by edsilv** 2017-11-27 13:57 UTC
Labels: bug, open collective
