### ISSUE TITLE
Possibility to use uv with dynamic manifest

### ISSUE THREAD

**Issue by Daniel-KM** [UniversalViewer/universalviewer#663] opened 2019-04-05 09:49 UTC
Hi,

For a project, I need UV to work offline. But manifests are created offline too from another js library too, and uv cannot load them: it requires a url for iiifResourceUri, not a real json object. 

So do you have an idea to bypass this issue? 

In fact, it seems to be possible to make some changes to this and to bundle.js/getData() and UrlParse() to fix it, but I prefer not to hack uv and keep the official releases.

Thanks,

**Comment by demiankatz** [comment] 2019-04-05 11:01
Can the manifests be written to disk and loaded with file:// URLs, or do you need to pass the data directly?

**Comment by Daniel-KM** [comment] 2019-04-05 11:48
I need to pass the data directly, because they are built dynamically by a js library. Original records are stored, but they are not manifests, so there is a js library that converts them into manifests in real time.

**Comment by irv** [comment] 2019-07-25 10:31
https://github.com/UniversalViewer/user-stories/issues/43

**Comment by LlGC-szw** [comment] 2023-08-25 11:52
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment] 2023-09-28 15:21
Closing as duplicate of linked user story above.

**Closed by demiankatz** 2023-09-28 15:21 UTC
