### ISSUE TITLE
Embed functionality with https

### ISSUE THREAD

**Issue by BinaryRoads** [UniversalViewer/universalviewer#410] opened 2016-11-10 12:28 UTC
The viewer is hosted on a https domain and when there are customers who want to embed the viewer in a standard http domain the bundle.min.js gives an error.

TypeError: related is undefined
	
...){var related=this.getRelated();return related.length&&(related=related[0]),"tex...
	
bundle.min.js (regel 9, kol 25297)

It works when we have a viewer on an http domain and embed on a http domain, it also works fine when we have a viewer on a https domain and embed it on a https domain. 

Is there any possibility that this can be fixed?

**Comment by edsilv** [comment] 2016-11-21 17:13
I have a hunch this might fix it: 

https://github.com/UniversalViewer/universalviewer/commit/50ee588bf174e79d4c87041a47387d2591ba1cad#diff-74085dae513d6ca88bc34b8f0eb26729R747

(dev branch)

**Comment by tjvc** [comment] 2016-12-21 12:31
I'm seeing the same issue. Embedding on external domains isn't working at all for me with either the master or dev builds. I think the issue is in [manifold](https://github.com/viewdir/manifold). Here's a pull request that I think should fix it, if that's useful: viewdir/manifold#1.

**Comment by edsilv** [comment] 2017-01-19 10:30
Yep, you were correct about it being manifold's `hasRelatedPage` method. This is now fixed on dev.

**Closed by edsilv** 2017-01-19 10:30 UTC
