### ISSUE TITLE
BL UV - Search - Highlighting does not fit entirely over word

### ISSUE THREAD

**Issue by psooben** [UniversalViewer/universalviewer#327] opened 2016-06-21 11:22 UTC
Used the following Ark:

http://accessdev.ad.bl.uk/item/viewer/ark:/81055/vdc_100022541999.0x000002#?si=0&ci=0&z=0.1965%2C-0.2922%2C2.2333%2C1.475&c=0&m=0&s=0&cv=22

1) Typed cigar in the search box.

--> Highlighted does not fit completely over the word cigar (but it's almost there)

TFS Ref: 11268

**Comment by irv** [comment] 2016-06-21 12:11
URL should be http://access.bl.uk/item/viewer/ark:/81055/vdc_100022541999.0x000002#?si=0&ci=0&z=0.0778%2C0.2566%2C1.1633%2C0.7436&c=0&m=0&s=0&cv=22
but more importantly, this is a dupe of #201

**Closed** 2016-07-05 10:51 UTC
Labels: bl
