### ISSUE TITLE
images in contentLeftPanel do not load in some cases

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#369] opened 2016-08-31 07:07 UTC
Clicking on the imageBtn "gallery" in the upper right corner,
there are three cases:
1. contentLeftPanel is open: panel expands and images load
2. someone closes contentLeftPanel, and then clicks on the gallery button: panel expands, but it contains empty "canvases" without images
3. contentLeftPanel is closed at start ( option "panelOpen" is false ), and someone clicks on the gallery button: panel  expands, but this time it is just a blank panel. It does not even contain the canvases.

**Comment by edsilv** [comment] 2016-11-16 14:59
closing at dupe of #407

**Closed by edsilv** 2016-11-16 14:59 UTC
