### ISSUE TITLE
collection viewer does not highlight link of current manifest in left panel

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#668] opened 2019-05-16 09:10 UTC
**UV version:**

```
 universalviewer@2.0.1
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

In the left panel, in the tab "index", you can switch to another manifest by clicking on its title.
The UV reloads, but the link is not highlighted as being active.

Links to ranges are highlighted, when there are clicked. Of course this different, as the UV does not reload ..

cf. http://universalviewer.io/uv.html?manifest=https%3A%2F%2Fadore.ugent.be%2FIIIF%2Fcollections%2FRUG01-001650955

**Expected behavior:**

In the manifest tree in the left panel, the UV should highlight the title of the active manifest/range always.

**Steps to reproduce:**

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by LlGC-szw** [comment] 2023-08-25 11:52
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment] 2023-11-02 16:35
I think this may still be an issue. See the closed duplicate ticket #887 for some additional insights that may be related. I was not able to fully test this because of authorization issues with the example link above.

**Comment by demiankatz** [comment] 2023-11-02 16:44
Cannot reproduce; problem appears to be resolved.

**Comment by LanieOkorodudu** [comment] 2024-08-20 15:06
I agree with you @demiankatz  that the link has authorization issues. I'm currently testing to see if the problem persists, despite the potential connection to the closed ticket #887, which may have addressed the issue. I attempted to replicate the issue using the latest sample version of UV with this [manifest](https://wellcomelibrary.org/iiif/b21274344/manifest). When clicking on each title under the index tab, as described, the selected title is still not highlighted, confirming that the issue remains unresolved.

**Comment by demiankatz** [comment] 2024-08-21 11:08
@LanieOkorodudu, I see the problem when I test in the old v4.0.0 at [uv-v4.netlify.app](https://uv-v4.netlify.app). However, it appears to be solved when I try the same thing at the latest code at [universalviewer.dev](https://www.universalviewer.dev). This suggests to me that the problem has actually been addressed. Are you seeing something different? If you're regularly testing with uv-v4, I'd suggest using the dev version instead in future to ensure that you're testing the latest code. I think there is an intention to eventually create a "latest v4 release" instance to capture the most recent release, instead of being stuck at 4.0.0 forever, but I don't believe anyone has had time to set it up yet.

**Comment by LanieOkorodudu** [comment] 2024-08-21 11:19
> @LanieOkorodudu, I see the problem when I test in the old v4.0.0 at [uv-v4.netlify.app](https://uv-v4.netlify.app). However, it appears to be solved when I try the same thing at the latest code at [universalviewer.dev](https://www.universalviewer.dev). This suggests to me that the problem has actually been addressed. Are you seeing something different? If you're regularly testing with uv-v4, I'd suggest using the dev version instead in future to ensure that you're testing the latest code. I think there is an intention to eventually create a "latest v4 release" instance to capture the most recent release, instead of being stuck at 4.0.0 forever, but I don't believe anyone has had time to set it up yet.

@demiankatz I appreciate you pointing this out. I haven’t tested it on the universalviewer.dev yet, but I’ll do so now and confirm if I get the same results as you. Thanks for the suggestion—testing against the dev version makes perfect sense to ensure we're working with the latest code. I'll follow up with my findings shortly. Also, your idea of creating a 'latest v4 release' instance sounds like a great way to avoid being stuck on version 4.0.0 indefinitely

**Comment by LanieOkorodudu** [comment] 2024-08-21 11:29
@demiankatz I just tested on the dev version, and you're right—the selected title is now highlighted as it should be. Is there a specific reason why this issue remains open, despite being resolved in the dev version?

**Comment by demiankatz** [comment] 2024-08-21 11:38
I didn't close it before because I was unable to test it with the original manifest. But since we seem to have confirmed a fix now, I will close it. Thanks for your help!

**Closed by demiankatz** 2024-08-21 11:38 UTC
Labels: bug, ACTIVE

**Comment by nicolasfranck** [comment] 2024-08-21 11:51
yes thanks, totally forgot about this ticket
