### ISSUE TITLE
show selected manifest in index

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#365] opened 2016-08-22 07:39 UTC
The index tab does not show you which manifest exactly is selected,
neither does it show in which range the viewer is.

**Comment by edsilv** [comment] 2016-08-25 11:51
This could be a good one to discuss on the community call in order to flesh out a bit.

**Comment by edsilv** [comment] 2016-09-01 15:37
Related? https://github.com/UniversalViewer/universalviewer/issues/302

**Comment by nicolasfranck** [comment] 2016-09-02 06:35
Yes indeed ;-)

**Comment by edsilv** [comment] 2017-04-14 11:54
closing as duplicate of #302

**Closed by edsilv** 2017-04-14 11:54 UTC
Labels: enhancement
