### ISSUE TITLE
Display number of search results in gallery

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#416] opened 2016-11-22 12:57 UTC
It would be good if users had a visual identifier of how many search results each item contains in the gallery. Something similar to these screenshots.

![screenshot from 2016-08-03 15 56 51](https://cloud.githubusercontent.com/assets/1083554/20524416/66053352-b0b2-11e6-8b37-5788bb1473d8.png)

![pasted_image_at_2016_11_21_02_57_pm](https://cloud.githubusercontent.com/assets/1083554/20524422/6e3d1850-b0b2-11e6-96a9-bab0a23fcae2.png)

**Comment by edsilv** [comment] 2016-11-23 14:01
Closing as dupe of #350

**Closed by edsilv** 2016-11-23 14:01 UTC
