### ISSUE TITLE
Paging toggle button always visible

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#225] opened 2016-01-21 15:45 UTC
The user should always be able to toggle between one up and two up states. Should default to what is specified in the manifest.

**Comment by LlGC-szw** [comment] 2023-08-25 11:40
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment] 2023-09-28 15:01
Duplicate of #114.

**Closed by demiankatz** 2023-09-28 15:01 UTC
Labels: dev call
